In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression, Lasso, Ridge, LogisticRegression
from sklearn.metrics import accuracy_score, auc, confusion_matrix, f1_score
import sklearn.model_selection as ms

In [2]:
reg_data = pd.read_csv('kc_house_data.csv')    #Regression Data
clf_data = pd.read_csv('Titanic Dataset.csv')    #Classification Data

reg_data.shape, clf_data.shape

((21613, 21), (891, 12))

In [3]:
reg_data.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7      1180.0              0   
1      7242     2.0           0     0  ...      7      2170.0            400   
2     10000     1.0           0     0  ...      6       770.0              0   
3      5000     1.0           0     0  ...      7      1050.0            910   
4      8080     1.0           0     0  ...      8      1680.0              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [4]:
clf_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

# Classification USing Logistic Regression

In [5]:
features = pd.DataFrame()
features['Pclass'] = clf_data['Pclass']
features['SibSp'] = clf_data['SibSp']
features['Parch'] = clf_data['Parch']
features['Fare'] = clf_data['Fare']

data = np.array(features)
labels = clf_data['Survived']

log_reg = LogisticRegression()

In [6]:
## Randomly sample cases to create independent training and test data
np.random.seed(9988)
indx = range(data.shape[0])
indx = ms.train_test_split(indx, test_size = 0.3)
x_train = data[indx[0],:]
y_train = np.ravel(labels[indx[0]])
x_test = data[indx[1],:]
y_test = np.ravel(labels[indx[1]])

In [7]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(623, 4)
(623,)
(268, 4)
(268,)


In [8]:
log_reg.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [9]:
y_pred = log_reg.predict(x_test)

In [11]:
y_proba = log_reg.predict_proba(x_test)    #predicting probabilities for setting cut off value

adjusted1 = []
for i in y_proba:
    adjusted1.append(i[0])
    
adjusted2 = np.array(adjusted1)
    
print(y_proba.shape)
print(np.array(adjusted2.shape))

(268, 2)
[268]


In [13]:
print(adjusted2[:20])
print(y_pred[:20])

[0.76157227 0.51684689 0.76097895 0.43461159 0.28630929 0.76097895
 0.76157227 0.34937882 0.30834454 0.76147753 0.52577491 0.56362331
 0.43621515 0.69310339 0.78418368 0.6497689  0.76147753 0.76155602
 0.76152081 0.42075033]
[0 0 0 1 1 0 0 1 1 0 0 0 1 0 0 0 0 0 0 1]


In [15]:
confusion_matrix(y_test, y_pred)

array([[132,  24],
       [ 61,  51]])

In [16]:
accuracy_score(y_test, y_pred)

0.6828358208955224

In [17]:
log_reg1 = LogisticRegression(C=0.1)

In [18]:
log_reg1.fit(x_train, y_train)

LogisticRegression(C=0.1, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [19]:
y_pred1 = log_reg1.predict(x_test)
confusion_matrix(y_test, y_pred1)

array([[133,  23],
       [ 62,  50]])