# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.# 

In [1]:
import numpy as np

In [5]:
arr = np.arange(10,40,5)
arr

array([10, 15, 20, 25, 30, 35])

### Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists
Note: numpy index starts from zero

In [6]:
arr[2] # select the element at index 2

20

In [7]:
arr[5]

35

### Slicing

slicing is used when selecting more than one elemnt from numpy array

In [8]:
arr[2:] # select element from index 2 to the end of the array

array([20, 25, 30, 35])

In [11]:
arr[-1] # select the last element from the array

35

In [13]:
arr[2:5] # select the array element starting from index 2, and stop index 5, NOTE element at index 5 is not inclusive.

array([20, 25, 30])

### Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [15]:
arr2 = np.arange(0,11)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
#Setting a value with index range (Broadcasting)
arr2[0:5]=100

#Show
arr2

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [17]:
#Important notes on Slices
slice_of_arr = arr2[0:6]

#Show slice
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [18]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [19]:
arr2

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [20]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([10, 15, 20, 25, 30, 35])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity

In [29]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [30]:
#Indexing row 1
arr_2d[1]

array([20, 25, 30])

In [31]:
#indexing column 1
arr_2d[:,1]

array([10, 25, 40])

In [33]:
# indexing element in (row1,column 1)
arr_2d[1,1]

25

## Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [35]:
#Set up matrix
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [36]:
#Length of array
arr_length = arr2d.shape[1]

In [37]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following.
Note that two square bracket is used.

In [39]:

arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [40]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

### More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to fins useful images, like this one:

<img src= 'http://memory.osu.edu/classes/python/_images/numpy_indexing.png' width=500/>

Also, you can read up from the textbook sent

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [41]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [44]:
bool_arr = arr>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [45]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [46]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# Great Job!